### ISSUE TITLE
sample weights with few controls

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#108]
Currently the sample weights are set to `1` for cases and `1/p_control` for controls. The sampler actually returns `N = ceiling(n_controls * p_control)`.  The ceiling is there so that at least 1 control is selected if possible.

For small numbers of controls, the sample weights will be quite wrong I think. Consider,
```
p_control = 0.01
n_controls = 7 # only few patients at this time point
N = ceiling(n_controls * p_control) = 1
sample_weight = 1/0.01 = 100
```
I suppose we should give the actual sample proportion?
```
sample_weight = n_controls/N = 7/1 = 7
```

Perhaps also a minimum threshold to include all records? So if `n_controls < 20` don't sample.
@lisu-stats

**Comment by lisu-stats** [comment]
@gravesti Yes, I think we should use the actual sample proportion for the sample weights. And it is a good idea to set the minimum threshold when controls are small. Should we allow users to specify this threshold?

**Comment by gravesti** [comment]
@lisu-stats 
Ok. Yes, how about 
```
sampling_threshold: if there are fewer control observations than this threshold then all observations will be included in the sampled data (default = 20).
```

**Comment by lisu-stats** [comment]
@gravesti Sounds good. Thank you.

**Comment by gravesti** [comment]
I've fixed the sample weights.

I think I might change `sampling_threshold` to `min_samples`, because with the solution proposed above you get inconsistent numbers of controls, eg with `p_control = 0.01` for 200 expanded controls you get 2 samples and for 20 controls you get all 20. 

`min_samples: the minimum number of controls to return for a trial/follow-up time. Sampling is done without replacement, 
so actual number of sampled controls may be lower.`

This way we'd have `min_samples = 5` and we'd always get 5 samples, until the number of controls is >500.

**Comment by lisu-stats** [comment]
@gravesti This looks fine to me. But I would like to ask Shaun to confirm. 

@shaun2022 Shaun, basically, we'd like to set the minimum number of controls to sample along with a sampling proportion in the case-control sampling. For example, if `min_sample=5` and there are 100 potential controls and the sampling proportion is set as `p_control=0.01`, we sample 5 controls, not 1 control based on the sampling proportion.

**Comment by gravesti** [comment]
- [ ] Remove argument `sample_all_times` and code for `sample_all_times = FALSE`. Only implement `sample_all_times = TRUE` code path.
