### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#131]

**Comment by lisu-stats** [comment]
@gravesti I've changed the documentation for the main functions, but there were some styling errors after I committed the changes. It is likely due to some line spacing issues.

**Comment by gravesti** [comment]
Thanks for all of that @lisu-stats 
I will tidy up as needed

**Comment by lisu-stats** [comment]
@gravesti Sorry, Isaac. Just spotted some errors in the updated documentation. Is it OK to reopen the branch for me to correct them? Thank you.

**Comment by gravesti** [comment]
@lisu-stats I've opened a new branch https://github.com/Causal-LDA/TrialEmulation/tree/131_more_docs_changes

**Comment by lisu-stats** [comment]
@gravesti Thanks a lot. I've corrected the errors. It may be helpful to change the plotting ranges of cumulative incidence in the example of the `predict()` function. All others look great to me.

**Comment by gravesti** [comment]
Thanks again. I've changed the y limits. Shall I merge this now?
 @lisu-stats

**Comment by lisu-stats** [comment]
@gravesti Yes, please. Thanks a lot, Isaac.
