### ISSUE TITLE
censoring in data_manipulation step creates gaps

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#135]
@lisu-stats I was looking at some ways to improve performance of expansion and I came across some unexpected (to me) behaviour. 
When treatment switching censoring is turned on, some patient observations are deleted before the weighting step if there is a treatment switch. However if the patient later has `eligible == TRUE`, those later records are retained, creating a gap in the follow up. 
Do you think this is a problem?

**Comment by lisu-stats** [comment]
@gravesti Thanks for checking. These gaps are expected. The program will keep the treatment sequence data up to the first time point that an eligible patient switched treatment. But if the patient is later eligible for another trial, his/her treatment data from this trial baseline until the first treatment switching time will be kept for weight estimation.  We follow the SAS macro for this estimation strategy. I describe this on the top of page 12 of the manuscript.

**Comment by gravesti** [comment]
Ok, thanks for confirming. I will need to think a bit more on how to handle these gaps in my fast expanding approach.
I will proceed with publishing the current version to CRAN.

**Comment by lisu-stats** [comment]
Thanks, @gravesti I will finalize the manuscript and add the new CRAN version number (once published) next week

**Comment by gravesti** [comment]
@lisu-stats The package has been accepted to CRAN. I guess the updated windows version should be available tomorrow

**Comment by lisu-stats** [comment]
Thank you so much @gravesti
