### ISSUE TITLE
add show methods

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#170]
Review existing show/print methods and add more

- `@expansion`
- `@expansion@datastore`
- loaded outcome data (would need to save the parameters used when loading/sampling)

## change printing of input data
- [ ] don't show head of input data
- [ ] just print column names?

## outcome model
- [x] show method for te_outcome_model
  - [x] add to `trial_sequence` show method
  - [x] delete show method for trial_Sequence child classes
  - [x] incorporate switch_model printing in show(trial_sequence) (See below)

```r
if (.hasSlot(object, "switch_weights")) {
      catn("")
      catn("IPW for treatment switch censoring:")
      show(object@switch_weights)
    }
```

**Comment by darkgoldenrod-cherry** [comment]
```
get_show_methods <- function() {
  names <- ls(getNamespace("TrialEmulation"), all.names = TRUE)
  classes <- data.frame(
    "class" = grep(x = names, pattern = ".__C__", value = TRUE) |>
      substr(7, 100)
    )
  show_methods <- data.frame("class" = names(TrialEmulation:::`.__T__show:methods`), "show_method_exists" = TRUE)
  df <- merge(show_methods, class, by = "class", all.y = TRUE)
  df[is.na(df)] = FALSE
  df
}
```
