### ISSUE TITLE
Design for prediction methods and classes

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#174]
Once we have fitted the outcome model, we can do g-computation.

See `predict.TE_msm()` for previous implementation.

For now we can try to adapt that top level function to a trial_sequence object.

- [ ] `predict` is already an S3 generic
  - [ ] see other cases where we define S3 and S4 methods for a class
- [ ] Review what the needed inputs are. I think
  - [ ] trial_sequence object, trial_period to predict using, followup_times to predict at
  - [ ] Whether to calculate CIs and how many iterations
  - [ ] That will depend on the class of the model_fitter
    - [ ] Like what we have for the datastore classes, we need a single help page for each model_fitter describing the weight fitting, outcome fitting and prediction methods.
- [ ] What is needed in predicted object/class? predictions under each treatment level and the difference?

**Comment by gravesti** [comment]
Define `predict.trial_sequence_itt <- function(object, ...)`
Then `setMethod("predict", "trial_sequence_itt", predict.trial_sequence_itt)`

**Comment by gravesti** [comment]
See `marginaleffects` package at https://marginaleffects.com/vignettes/get_started.html
Potentially we can make use of their implementation
-[ ] check if we get the same results, following the https://marginaleffects.com/vignettes/gcomputation.html and https://marginaleffects.com/vignettes/comparisons.html#average-contrasts
Possibly advantage is compatibility with tidymodels

**Comment by igrave** [comment]
could be faster than `apply(x, 1, cumprod)`:
```r
cumprod.matrix = function(x) {
  y = matrix(1, nrow = dim(x)[1], ncol = dim(x)[2])
  y[, 1] = x[, 1]
  for (i in 2:dim(x)[2])
    y[, i] = y[, i - 1] * x[, i]
  return(y)
}
colMeans(cumprod.matrix(xmat))
```
