### ISSUE TITLE
suggest including numerator terms in outcome models

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#180]
`set_switch_weight_model` and `set_censor_weight_model` could check if the terms in the numerator formula have been included in the outcome model and if not suggest the user to include them.

@lisu-stats Is this reasonable?

**Comment by lisu-stats** [comment]
@gravesti Yes, I think this is a good idea. This point can be easily missed by users.

**Comment by gravesti** [comment]
- Could we automatically add the numerator terms to the outcome model? Is there any setting where we might not want them included?
- If the numerator models are pooled, do they still need to be in the outcome model?
@lisu-stats

**Comment by lisu-stats** [comment]
Yes, the numerator terms in the weights model can be automatically added to the outcome model, but we shall provide the users an alert for this step. They may include interactions of the numerator terms with time or treatments if needed, so the actual outcome model may be more complicated than including the covariates in the numerator model.

Pooling the numerator models means that we don't stratify by previous treatments, but we can still condition on other covariates, which in this case requires that these covariates be included in the outcome model.

**Comment by gravesti** [comment]
Let's add a function within set_outcome_model and set_weight functions to add numerator terms and message if terms have been added.

**Comment by lisu-stats** [comment]
Great, thank you @gravesti
