### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#196]
- [x] Review new-interface vignette and update
- [x] Review show functions
- [x] Add @darkgoldenrod-cherry to authors
- [x] NEWS
- [x] Make sure checks will pass on CRAN

**Comment by gravesti** [comment]
We need to update on CRAN before the 10th Sept as the partial matching becomes a problem.

**Comment by lisu-stats** [comment]
Thanks for letting me know @gravesti  Do you want me to test the previous  example using the new functionality this week?

**Comment by gravesti** [comment]
That would be great if you have the time. If there are any big changes we might have to do another update in the next weeks. All the new functions are marked as experiments, so I think it's ok.

**Comment by lisu-stats** [comment]
@gravesti I just had a quick run using the previous simulated data and the new functions. The results are consistent with those using previous functions.

I have a couple of questions:

1) How do we inspect the data used for fitting the weight models? 

2) The variable '`time_on_regime`' was created after running `set_data()`. I understand that this variable will be used in the weight models. But it was also included in the final expanded data, and this could be confusing as I don't think it can be used in the MSM for outcomes. We could use '`followup_time`' instead in the MSM.  

Thanks.

**Comment by gravesti** [comment]
1. Would you like to look at the subset of the data used to fit the specific weighting model, eg with previous treatment =1 ? Or the whole "observational" data, like we have a function `outcome_data()`?
2. I will make sure that `time_on_regime` does not get into the expanded dataset

@lisu-stats 
Since time was running out, I put a new version on CRAN that only fixed that urgent problem. I will update with these changes shortly.

**Comment by lisu-stats** [comment]
Thanks @gravesti 
I would like to have a look at the subset of the data that were used to fit the weight models.

**Comment by lisu-stats** [comment]
@gravesti How frequently we should update the package to prevent being removed from CRAN?

**Comment by gravesti** [comment]
There is no fixed timetable. It's on an as-needed basis. In this case there
a change in the data.table package which exposed a bug in our code.
Therefore we needed to update in a timely manner so that CRAN remains in a
consistent working state.

**Comment by gravesti** [comment]
Close with updates in #211
