### ISSUE TITLE
package logo

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#197]
@lisu-stats I'm thinking we could add a logo for the package.

![TrialEmulation-v3](https://github.com/user-attachments/assets/0f225e3c-0143-4410-a407-e5dcf61ea71d)

**Comment by lisu-stats** [comment]
Thanks, @gravesti  Is it an emu in the logo? Nice choice!

**Comment by gravesti** [comment]
Yes, exactly. Ok, I will go ahead with this one

**Comment by lisu-stats** [comment]
Thanks. @gravesti My colleague suggested that we may have a "sequence of emu" perhaps overlapping to highlight sequential trial emulation

**Comment by lisu-stats** [comment]
Thanks @gravesti The emus look good, but they make the logo a bit crowded in the middle. Can we fiddle a bit the layout of the title and the figure? Thank you

**Comment by gravesti** [comment]
![TrialEmulation-seq-v4](https://github.com/user-attachments/assets/17f46f4e-dfc7-4426-93ec-6b77ced98fd2)
Maybe like that?
I do like the original one for its simplicity still.

**Comment by lisu-stats** [comment]
@gravesti I agree the original one is more clean and simple. Let's just use that. Thank you so much for trying out more with the design.

**Comment by gravesti** [comment]
Alright. In any case, if we come up with something nicer in future we can change it any time.

**Comment by lisu-stats** [comment]
Yes, we can update it in the future. Thanks @gravesti
