### ISSUE TITLE
New Interface Review

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#202]
- [x] Vignette text
- [x] Show methods

**Comment by lisu-stats** [comment]
@gravesti In function `set_outcome_model`, how do we specify interactions terms between covariates and `assigned_treatment`? Do we need to create them manually? Thanks.

**Comment by gravesti** [comment]
@lisu-stats You can include `assigned_treatment` terms in the formula for `adjustment_terms ` (or also `followup_time_terms`)

**Comment by lisu-stats** [comment]
@gravesti Thanks. I tried it but got the following error message. 

![Image](https://github.com/user-attachments/assets/4f06ebaf-9a1a-4b06-a66f-8ee9f1c5acdb)

**Comment by lisu-stats** [comment]
@gravesti It is weird I got different results when applying the following model. Basically, I added the interaction term in `treatment_var`, but I cannot specify both the options for trial period and followup_time. 

![Image](https://github.com/user-attachments/assets/f59d4fca-aac6-4261-8cdb-fe00d38cad03)
