### ISSUE TITLE
don't expand time_on_regime

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#205]
`time_on_regime` is created for use in weight models. It should not be included in the variables to expand

**Comment by gravesti** [comment]
@lisu-stats I was not able to find an instance where `time_on_regime` was included in the expanded data. Do you have an example?

**Comment by gravesti** [comment]
@lisu-stats 
Thanks for sending this example. I see it comes because we have `time_on_regime` in the numerator formula and we now automatically add these to the variables to be expanded because we will include them in the outcome model.
What's correct here?

```r
 set_switch_weight_model(
  trial_pp,
  denominator = ~ X1 + X2 + X3 + X4 + age_s  + time_on_regime + I(time_on_regime^2),
  numerator = ~ X3 + X4 + time_on_regime + I(time_on_regime^2),
  model_fitter = stats_glm_logit(save_path = file.path(trial_pp_dir, "switch_models"))
)
```

**Comment by lisu-stats** [comment]
@gravesti Thank you for checking on this. 

I think here to avoid confusion about the time origins in the unexpanded and expanded data, `time_on_regime` should not be included in the numerator model of the weights. I just checked the SAS macro documentation, they mentioned this as well. 
Sorry about my mistake in the code.  If we can add some warning that the  `time_on_regime` variable should not be included the numerator, that would be great!

**Comment by gravesti** [comment]
Sure, good idea. I can add a check for that.
