### ISSUE TITLE
How do we inspect the data used for fitting the weight models?

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#206]
Currently we do not know which data is used to fit the individual weight models.

Some approaches:
1. If we have saved the weight models to disk, we can load the full objects and inspect the data contained in the weight model.
2. We could have indicator variables for which observations were used in each model.

**Comment by lisu-stats** [comment]
@gravesti 1) seems straightforward, but because of the stratification by previous treatments in the models, it might not be easy to compare these data with the original data from the users. So if it is not too much hassle, implementing 2 is good.

**Comment by gravesti** [comment]
@lisu-stats I have implemented both changes in this branch. After you have another look, I propose we publish this new version

**Comment by lisu-stats** [comment]
Thanks a lot @gravesti  How do I install this branch?

**Comment by gravesti** [comment]
@lisu-stats This should work:

remotes::install_github("Causal-LDA/TrialEmulation", ref = "206-weight_model_data")

**Comment by lisu-stats** [comment]
I have had a go with the new functions @gravesti They look fine to me.  Just wondering what is the difference by using `observed_data()` and directly checking the list `data `under the object say, `trial_pp`?

**Comment by gravesti** [comment]
Using the function would give us the possibility to hide some of the derived columns that are not of interest to the user, eg `am_1`, `first` etc.

**Comment by lisu-stats** [comment]
I see. Thanks @gravesti  I think maybe we can change the function name to `IPW_data() `，so it does not mix up with the `outcome_data()`
