### ISSUE TITLE
Accessing the 'New Interface'

### ISSUE THREAD

**Issue by rambles** [Causal-LDA/TrialEmulation#207]
Hi

I've just come across the TrialEmulation package and it looks perfect for a project I'm working ... so well done!

I'm trying to run through the 'New Interface' vignette, but none of the 'experimental' functions are available.  

How come?  Have they been removed for the 0.0.3.9 release (the doc is for 0.0.3.6)?

Thanks, Rich

**Comment by gravesti** [comment]
Hi @rambles 
Thanks for your interest in our package! A new release CRAN with the new interface is imminent. For now you will have to install from github to use those functions.

**Comment by rambles** [comment]
I see the new release.  That's great, thanks.
